name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # تم استبدال v4 بالكود الطويل الخاص بها
      - uses: actions/checkout@692973e3d937129bcbf406528e2856e368273633 
      
      # تم استبدال v4 بالكود الطويل الخاص بها
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 
        with:
          node-version: '18'
          cache: 'npm'
          
      - run: npm ci
      - run: npm run build
      
      # تم استبدال v3 بالكود الطويل الخاص بها
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa 
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # تم استبدال v4 بالكود الطويل الخاص بها
      - uses: actions/deploy-pages@d6db90164ad5b118d2d652a80c7514659966df30 
        id: deployment
